In [2]:
import random
from datetime import datetime, timedelta
from pathlib import Path

import pandas as pd

In [3]:
random.seed(42)

BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

print("Base directory:", BASE_DIR)
print("Data directory:", DATA_DIR)

Base directory: c:\Users\spund\OneDrive\Documents\job-matching-mvp
Data directory: c:\Users\spund\OneDrive\Documents\job-matching-mvp\data

In [4]:
skills_taxonomy = [
    {"skill_id": "S001", "skill_name": "SQL", "skill_category": "Data", "aliases": "sql,structured query language"},
    {"skill_id": "S002", "skill_name": "Excel", "skill_category": "Data", "aliases": "excel,microsoft excel,spreadsheets"},
    {"skill_id": "S003", "skill_name": "Power BI", "skill_category": "Data Visualization", "aliases": "power bi,powerbi,bi dashboard"},
    {"skill_id": "S004", "skill_name": "Python", "skill_category": "Programming", "aliases": "python,python programming"},
    {"skill_id": "S005", "skill_name": "Communication", "skill_category": "Soft Skills", "aliases": "communication,verbal communication,written communication"},
    {"skill_id": "S006", "skill_name": "Stakeholder Management", "skill_category": "Business", "aliases": "stakeholder management,stakeholder engagement,managing stakeholders"},
    {"skill_id": "S007", "skill_name": "Agile", "skill_category": "Project Management", "aliases": "agile,scrum,kanban"},
    {"skill_id": "S008", "skill_name": "Jira", "skill_category": "Project Management", "aliases": "jira,atlassian jira"},
    {"skill_id": "S009", "skill_name": "Risk Management", "skill_category": "Project Management", "aliases": "risk management,risk assessment"},
    {"skill_id": "S010", "skill_name": "Documentation", "skill_category": "Operations", "aliases": "documentation,technical documentation,report writing"},
    {"skill_id": "S011", "skill_name": "Data Cleaning", "skill_category": "Data", "aliases": "data cleaning,data wrangling,data preparation"},
    {"skill_id": "S012", "skill_name": "APIs", "skill_category": "Programming", "aliases": "apis,api integration,rest api,rest apis"},
    {"skill_id": "S013", "skill_name": "Git", "skill_category": "Programming", "aliases": "git,version control,github"},
    {"skill_id": "S014", "skill_name": "Reporting", "skill_category": "Operations", "aliases": "reporting,report generation,business reporting"},
    {"skill_id": "S015", "skill_name": "Process Improvement", "skill_category": "Operations", "aliases": "process improvement,continuous improvement,process optimization"},
    {"skill_id": "S016", "skill_name": "Cloud", "skill_category": "Infrastructure", "aliases": "cloud,cloud computing,aws,azure,gcp"},
    {"skill_id": "S017", "skill_name": "Docker", "skill_category": "Infrastructure", "aliases": "docker,containerization,containers"},
    {"skill_id": "S018", "skill_name": "Problem Solving", "skill_category": "Soft Skills", "aliases": "problem solving,analytical thinking"},
    {"skill_id": "S019", "skill_name": "Teamwork", "skill_category": "Soft Skills", "aliases": "teamwork,collaboration,team collaboration"},
    {"skill_id": "S020", "skill_name": "Customer Service", "skill_category": "Operations", "aliases": "customer service,client support,customer support"},
    {"skill_id": "S021", "skill_name": "Data Analysis", "skill_category": "Data", "aliases": "data analysis,analytics,analytical skills"},
    {"skill_id": "S022", "skill_name": "Tableau", "skill_category": "Data Visualization", "aliases": "tableau,tableau dashboard"},
    {"skill_id": "S023", "skill_name": "Project Coordination", "skill_category": "Project Management", "aliases": "project coordination,project support,coordination"},
    {"skill_id": "S024", "skill_name": "Recruitment", "skill_category": "HR", "aliases": "recruitment,talent acquisition,hiring"},
    {"skill_id": "S025", "skill_name": "CV Screening", "skill_category": "HR", "aliases": "cv screening,resume screening,profile screening"},
]

skills_df = pd.DataFrame(skills_taxonomy)
skills_df.head()

,skill_id,skill_name,skill_category,aliases
0,S001,SQL,Data,"sql,structured query language"
1,S002,Excel,Data,"excel,microsoft excel,spreadsheets"
2,S003,Power BI,Data Visualization,"power bi,powerbi,bi dashboard"
3,S004,Python,Programming,"python,python programming"
4,S005,Communication,Soft Skills,"communication,verbal communication,written com..."

In [5]:
locations = ["Mumbai", "Pune", "Delhi", "Bengaluru", "Hyderabad", "Dubai"]
education_levels = ["Bachelor", "Master"]
work_modes = ["Onsite", "Hybrid", "Remote"]

first_names = [
    "Ravi", "Aisha", "Neha", "Arjun", "Sana", "Karan", "Priya", "Rohit", "Meera",
    "Imran", "Farah", "Vikram", "Ananya", "Rahul", "Fatima", "Aman", "Nisha",
    "Kabir", "Pooja", "Aditya", "Isha", "Yusuf", "Sneha", "Dev", "Tanya"
]

last_names = [
    "Patil", "Khan", "Sharma", "Mehta", "Iqbal", "Desai", "Nair", "Verma", "Joshi",
    "Shaikh", "Ali", "Rao", "Kapoor", "Malhotra", "Singh", "Jain", "Kulkarni",
    "Fernandes", "Gupta", "Menon"
]

job_templates = [
    {
        "category": "Data Analyst",
        "titles": ["Junior Data Analyst", "BI Analyst", "Reporting Analyst", "Data Insights Associate"],
        "required_skills": ["SQL", "Excel", "Power BI", "Data Analysis"],
        "preferred_skills": ["Python", "Data Cleaning", "Communication", "Tableau"],
        "description": "Analyze data, build reports, and support decision-making through dashboards and insights."
    },
    {
        "category": "Software Engineer",
        "titles": ["Backend Analyst", "Software Engineer", "API Developer", "Cloud Support Engineer"],
        "required_skills": ["Python", "SQL", "APIs", "Git"],
        "preferred_skills": ["Docker", "Cloud", "Problem Solving", "Teamwork"],
        "description": "Build backend services, work with APIs, and support engineering delivery."
    },
    {
        "category": "Project Manager",
        "titles": ["Project Coordinator", "Technical Project Associate", "Delivery Associate", "Program Coordinator"],
        "required_skills": ["Communication", "Stakeholder Management", "Documentation", "Project Coordination"],
        "preferred_skills": ["Agile", "Jira", "Risk Management", "Teamwork"],
        "description": "Coordinate projects, manage stakeholders, and support delivery execution."
    },
    {
        "category": "Operations",
        "titles": ["Operations Analyst", "Program Operations Specialist", "Operations Associate", "Process Analyst"],
        "required_skills": ["Excel", "Reporting", "Communication", "Process Improvement"],
        "preferred_skills": ["Stakeholder Management", "Documentation", "Teamwork", "Customer Service"],
        "description": "Drive reporting, improve workflows, and support operational efficiency."
    },
    {
        "category": "HR",
        "titles": ["HR Operations Associate", "Talent Acquisition Coordinator", "Recruitment Analyst", "People Operations Associate"],
        "required_skills": ["Communication", "Recruitment", "CV Screening", "Documentation"],
        "preferred_skills": ["Excel", "Teamwork", "Stakeholder Management", "Customer Service"],
        "description": "Support recruitment workflows, candidate screening, and people operations reporting."
    },
    {
        "category": "Customer Support",
        "titles": ["Customer Support Associate", "Client Success Coordinator", "Support Operations Analyst", "Service Desk Associate"],
        "required_skills": ["Communication", "Customer Service", "Documentation", "Teamwork"],
        "preferred_skills": ["Reporting", "Excel", "Problem Solving", "Stakeholder Management"],
        "description": "Handle user support, document issues, and ensure service quality."
    },
]

courses_master = [
    ("SQL for Analysts", "Coursera", "SQL", 4, "Beginner", "Online"),
    ("Advanced Excel for Business", "Udemy", "Excel", 3, "Beginner", "Online"),
    ("Power BI Dashboarding", "Udemy", "Power BI", 3, "Beginner", "Online"),
    ("Python for Data Work", "Coursera", "Python", 5, "Intermediate", "Online"),
    ("Business Communication Essentials", "edX", "Communication", 2, "Beginner", "Online"),
    ("Stakeholder Management Basics", "LinkedIn Learning", "Stakeholder Management", 2, "Beginner", "Online"),
    ("Agile Fundamentals", "Coursera", "Agile", 2, "Beginner", "Online"),
    ("Jira for Teams", "Udemy", "Jira", 2, "Beginner", "Online"),
    ("Risk Management Essentials", "Coursera", "Risk Management", 4, "Intermediate", "Online"),
    ("Technical Documentation Basics", "LinkedIn Learning", "Documentation", 2, "Beginner", "Online"),
    ("Data Cleaning with Python", "Udemy", "Data Cleaning", 3, "Intermediate", "Online"),
    ("REST API Fundamentals", "Udemy", "APIs", 3, "Beginner", "Online"),
    ("Git and Version Control", "Coursera", "Git", 2, "Beginner", "Online"),
    ("Reporting for Analysts", "edX", "Reporting", 2, "Beginner", "Online"),
    ("Process Improvement Basics", "Coursera", "Process Improvement", 3, "Beginner", "Online"),
    ("Cloud Computing Foundations", "Google", "Cloud", 4, "Beginner", "Online"),
    ("Docker Essentials", "Udemy", "Docker", 2, "Beginner", "Online"),
    ("Problem Solving and Critical Thinking", "edX", "Problem Solving", 2, "Beginner", "Online"),
    ("Recruitment Foundations", "LinkedIn Learning", "Recruitment", 3, "Beginner", "Online"),
    ("Resume Screening and Shortlisting", "Udemy", "CV Screening", 2, "Beginner", "Online"),
    ("Tableau Dashboard Design", "Coursera", "Tableau", 3, "Beginner", "Online"),
    ("Customer Service Fundamentals", "LinkedIn Learning", "Customer Service", 2, "Beginner", "Online"),
    ("Project Coordination Basics", "Coursera", "Project Coordination", 2, "Beginner", "Online"),
]

In [6]:
def make_id(prefix: str, n: int, width: int = 3) -> str:
    return f"{prefix}{str(n).zfill(width)}"


def random_name() -> str:
    return f"{random.choice(first_names)} {random.choice(last_names)}"


def sample_skills(required_skills, preferred_skills, min_total=5, max_total=8):
    skills = set()

    # Most candidates should have decent overlap with their preferred category
    req_count = random.randint(max(2, len(required_skills) // 2), len(required_skills))
    pref_count = random.randint(1, min(3, len(preferred_skills)))

    skills.update(random.sample(required_skills, req_count))
    skills.update(random.sample(preferred_skills, pref_count))

    all_skills = list(skills_df["skill_name"])
    target_count = random.randint(min_total, max_total)

    while len(skills) < target_count:
        skills.add(random.choice(all_skills))

    return sorted(skills)


def compute_match_score_for_generation(candidate_skills, job_required_skills, exp_years, min_exp, education, required_edu,
                                       candidate_location, job_location, desired_category, job_category):
    candidate_set = set(s.lower() for s in candidate_skills)
    required_set = set(s.lower() for s in job_required_skills)

    skill_score = len(candidate_set & required_set) / len(required_set) if required_set else 0
    exp_score = 1.0 if exp_years >= min_exp else round(exp_years / min_exp, 2) if min_exp > 0 else 1.0

    edu_rank = {"High School": 1, "Diploma": 2, "Bachelor": 3, "Master": 4, "PhD": 5}
    edu_score = 1.0 if edu_rank.get(education, 0) >= edu_rank.get(required_edu, 0) else 0.0

    loc_score = 1.0 if candidate_location == job_location else 0.5
    pref_score = 1.0 if desired_category == job_category else 0.4

    score = (0.5 * skill_score + 0.2 * exp_score + 0.1 * edu_score + 0.1 * loc_score + 0.1 * pref_score) * 100
    return round(score, 1)


def weighted_status_from_score(score):
    if score >= 90:
        return random.choices(
            ["Interviewed", "Placed", "Applied"],
            weights=[40, 35, 25],
            k=1
        )[0]
    if score >= 80:
        return random.choices(
            ["Applied", "Interviewed", "Matched", "Placed"],
            weights=[40, 25, 25, 10],
            k=1
        )[0]
    if score >= 70:
        return random.choices(
            ["Matched", "Applied", "Interviewed", "Rejected"],
            weights=[40, 35, 10, 15],
            k=1
        )[0]
    return random.choices(
        ["Matched", "Rejected", "Applied"],
        weights=[50, 35, 15],
        k=1
    )[0]

In [7]:
num_jobs = 60
jobs = []

for i in range(1, num_jobs + 1):
    template = random.choice(job_templates)
    title = random.choice(template["titles"])
    category = template["category"]
    location = random.choice(locations)
    work_mode = random.choice(work_modes)
    min_exp = random.choice([1, 2, 3, 4, 5, 6])
    education_required = random.choice(["Bachelor", "Bachelor", "Bachelor", "Master"])

    required_count = random.randint(4, min(6, len(template["required_skills"])))
    preferred_count = random.randint(2, min(4, len(template["preferred_skills"])))

    required_skills = random.sample(template["required_skills"], required_count)
    preferred_skills = random.sample(template["preferred_skills"], preferred_count)

    jobs.append({
        "job_id": make_id("J", i),
        "title": title,
        "category": category,
        "location": location,
        "work_mode": work_mode,
        "min_experience": min_exp,
        "education_required": education_required,
        "required_skills": ",".join(required_skills),
        "preferred_skills": ",".join(preferred_skills),
        "description": template["description"],
    })

jobs_df = pd.DataFrame(jobs)
jobs_df.head()

,job_id,title,category,location,work_mode,min_experience,education_required,required_skills,preferred_skills,description
0,J001,Customer Support Associate,Customer Support,Mumbai,Remote,3,Bachelor,"Communication,Documentation,Teamwork,Customer ...","Reporting,Stakeholder Management","Handle user support, document issues, and ensu..."
1,J002,BI Analyst,Data Analyst,Pune,Remote,5,Bachelor,"Data Analysis,SQL,Excel,Power BI","Python,Tableau,Data Cleaning,Communication","Analyze data, build reports, and support decis..."
2,J003,Technical Project Associate,Project Manager,Pune,Hybrid,1,Bachelor,"Documentation,Stakeholder Management,Project C...","Teamwork,Risk Management","Coordinate projects, manage stakeholders, and ..."
3,J004,Data Insights Associate,Data Analyst,Mumbai,Remote,3,Bachelor,"SQL,Data Analysis,Power BI,Excel","Python,Tableau,Communication,Data Cleaning","Analyze data, build reports, and support decis..."
4,J005,Program Coordinator,Project Manager,Dubai,Hybrid,2,Bachelor,"Documentation,Project Coordination,Communicati...","Jira,Agile","Coordinate projects, manage stakeholders, and ..."

In [8]:
num_candidates = 250
candidates = []

for i in range(1, num_candidates + 1):
    preferred_template = random.choice(job_templates)
    desired_category = preferred_template["category"]

    years_experience = random.choice([0, 1, 2, 3, 4, 5, 6, 7, 8])
    education_level = random.choice(["Bachelor", "Bachelor", "Master"])
    location = random.choice(locations)

    skills = sample_skills(
        preferred_template["required_skills"],
        preferred_template["preferred_skills"],
        min_total=5,
        max_total=8
    )

    candidates.append({
        "candidate_id": make_id("C", i),
        "full_name": random_name(),
        "location": location,
        "education_level": education_level,
        "years_experience": years_experience,
        "desired_job_category": desired_category,
        "skills_list": ",".join(skills),
    })

candidates_df = pd.DataFrame(candidates)
candidates_df.head()

,candidate_id,full_name,location,education_level,years_experience,desired_job_category,skills_list
0,C001,Ravi Fernandes,Delhi,Bachelor,8,Project Manager,"Agile,Communication,Documentation,Jira,Problem..."
1,C002,Priya Menon,Mumbai,Bachelor,1,Operations,"Cloud,Communication,Git,Jira,Problem Solving,P..."
2,C003,Vikram Ali,Delhi,Bachelor,2,HR,"CV Screening,Cloud,Communication,Customer Serv..."
3,C004,Ananya Kapoor,Bengaluru,Bachelor,8,HR,"CV Screening,Cloud,Data Cleaning,Documentation..."
4,C005,Dev Iqbal,Mumbai,Bachelor,2,Customer Support,"Communication,Documentation,Excel,Reporting,St..."

In [9]:
courses = []

for i, course in enumerate(courses_master, start=1):
    course_name, provider, skill_covered, duration_weeks, difficulty, course_type = course
    courses.append({
        "course_id": make_id("CR", i),
        "course_name": course_name,
        "provider": provider,
        "skill_covered": skill_covered,
        "duration_weeks": duration_weeks,
        "difficulty": difficulty,
        "course_type": course_type,
    })

courses_df = pd.DataFrame(courses)
courses_df.head()

,course_id,course_name,provider,skill_covered,duration_weeks,difficulty,course_type
0,CR001,SQL for Analysts,Coursera,SQL,4,Beginner,Online
1,CR002,Advanced Excel for Business,Udemy,Excel,3,Beginner,Online
2,CR003,Power BI Dashboarding,Udemy,Power BI,3,Beginner,Online
3,CR004,Python for Data Work,Coursera,Python,5,Intermediate,Online
4,CR005,Business Communication Essentials,edX,Communication,2,Beginner,Online

In [10]:
applications = []
application_counter = 1
today = datetime(2026, 3, 10)

for _, candidate in candidates_df.iterrows():
    desired_jobs = jobs_df[jobs_df["category"] == candidate["desired_job_category"]].copy()

    # Also allow some adjacent-role applications so the data is not too clean
    adjacent_jobs = jobs_df[jobs_df["category"] != candidate["desired_job_category"]].sample(5, random_state=random.randint(1, 9999))
    candidate_job_pool = pd.concat([
        desired_jobs.sample(min(6, len(desired_jobs)), random_state=random.randint(1, 9999)),
        adjacent_jobs
    ]).drop_duplicates(subset=["job_id"])

    applied_jobs = candidate_job_pool.sample(random.randint(2, 4), random_state=random.randint(1, 9999))

    candidate_skills = [s.strip() for s in candidate["skills_list"].split(",")]

    for _, job in applied_jobs.iterrows():
        job_required_skills = [s.strip() for s in job["required_skills"].split(",")]

        match_score = compute_match_score_for_generation(
            candidate_skills=candidate_skills,
            job_required_skills=job_required_skills,
            exp_years=float(candidate["years_experience"]),
            min_exp=float(job["min_experience"]),
            education=candidate["education_level"],
            required_edu=job["education_required"],
            candidate_location=candidate["location"],
            job_location=job["location"],
            desired_category=candidate["desired_job_category"],
            job_category=job["category"],
        )

        status = weighted_status_from_score(match_score)
        status_date = today - timedelta(days=random.randint(1, 45))

        applications.append({
            "application_id": make_id("A", application_counter),
            "candidate_id": candidate["candidate_id"],
            "job_id": job["job_id"],
            "match_score": match_score,
            "application_status": status,
            "status_date": status_date.strftime("%Y-%m-%d"),
        })
        application_counter += 1

applications_df = pd.DataFrame(applications)
applications_df.head()

,application_id,candidate_id,job_id,match_score,application_status,status_date
0,A001,C001,J046,41.5,Matched,2026-01-27
1,A002,C001,J006,56.5,Matched,2026-02-28
2,A003,C002,J020,51.5,Rejected,2026-03-02
3,A004,C002,J051,24.9,Rejected,2026-02-11
4,A005,C002,J032,62.5,Rejected,2026-03-02

In [11]:
print("skills_taxonomy:", skills_df.shape)
print("candidates:", candidates_df.shape)
print("jobs:", jobs_df.shape)
print("courses:", courses_df.shape)
print("applications:", applications_df.shape)

print("\nApplication status distribution:")
print(applications_df["application_status"].value_counts())

print("\nJob category distribution:")
print(jobs_df["category"].value_counts())

print("\nCandidate desired category distribution:")
print(candidates_df["desired_job_category"].value_counts())

skills_taxonomy: (25, 4)
candidates: (250, 7)
jobs: (60, 10)
courses: (23, 7)
applications: (759, 6)

Application status distribution:
application_status
Matched        292
Applied        178
Rejected       149
Interviewed     91
Placed          49
Name: count, dtype: int64

Job category distribution:
category
Project Manager      16
Operations           13
Data Analyst          9
Software Engineer     8
HR                    8
Customer Support      6
Name: count, dtype: int64

Candidate desired category distribution:
desired_job_category
HR                   47
Customer Support     46
Project Manager      42
Data Analyst         40
Software Engineer    39
Operations           36
Name: count, dtype: int64

In [12]:
skills_df.to_csv(DATA_DIR / "skills_taxonomy.csv", index=False)
candidates_df.to_csv(DATA_DIR / "candidates.csv", index=False)
jobs_df.to_csv(DATA_DIR / "jobs.csv", index=False)
courses_df.to_csv(DATA_DIR / "courses.csv", index=False)
applications_df.to_csv(DATA_DIR / "applications.csv", index=False)

print("Files written successfully:")
for file_name in [
    "skills_taxonomy.csv",
    "candidates.csv",
    "jobs.csv",
    "courses.csv",
    "applications.csv",
]:
    print("-", DATA_DIR / file_name)

Files written successfully:
- c:\Users\spund\OneDrive\Documents\job-matching-mvp\data\skills_taxonomy.csv
- c:\Users\spund\OneDrive\Documents\job-matching-mvp\data\candidates.csv
- c:\Users\spund\OneDrive\Documents\job-matching-mvp\data\jobs.csv
- c:\Users\spund\OneDrive\Documents\job-matching-mvp\data\courses.csv
- c:\Users\spund\OneDrive\Documents\job-matching-mvp\data\applications.csv

In [13]:
display(candidates_df.head(10))
display(jobs_df.head(10))
display(applications_df.head(10))

,candidate_id,full_name,location,education_level,years_experience,desired_job_category,skills_list
0,C001,Ravi Fernandes,Delhi,Bachelor,8,Project Manager,"Agile,Communication,Documentation,Jira,Problem..."
1,C002,Priya Menon,Mumbai,Bachelor,1,Operations,"Cloud,Communication,Git,Jira,Problem Solving,P..."
2,C003,Vikram Ali,Delhi,Bachelor,2,HR,"CV Screening,Cloud,Communication,Customer Serv..."
3,C004,Ananya Kapoor,Bengaluru,Bachelor,8,HR,"CV Screening,Cloud,Data Cleaning,Documentation..."
4,C005,Dev Iqbal,Mumbai,Bachelor,2,Customer Support,"Communication,Documentation,Excel,Reporting,St..."
5,C006,Tanya Jain,Bengaluru,Bachelor,2,Operations,"Communication,Customer Service,Data Analysis,D..."
6,C007,Fatima Desai,Mumbai,Master,0,HR,"CV Screening,Communication,Customer Service,Ex..."
7,C008,Rahul Gupta,Mumbai,Bachelor,4,Customer Support,"Customer Service,Docker,Documentation,Jira,Sta..."
8,C009,Isha Joshi,Pune,Bachelor,2,Customer Support,"Documentation,Excel,Process Improvement,Report..."
9,C010,Meera Singh,Mumbai,Master,4,Operations,"Customer Service,Data Analysis,Excel,Process I..."

,job_id,title,category,location,work_mode,min_experience,education_required,required_skills,preferred_skills,description
0,J001,Customer Support Associate,Customer Support,Mumbai,Remote,3,Bachelor,"Communication,Documentation,Teamwork,Customer ...","Reporting,Stakeholder Management","Handle user support, document issues, and ensu..."
1,J002,BI Analyst,Data Analyst,Pune,Remote,5,Bachelor,"Data Analysis,SQL,Excel,Power BI","Python,Tableau,Data Cleaning,Communication","Analyze data, build reports, and support decis..."
2,J003,Technical Project Associate,Project Manager,Pune,Hybrid,1,Bachelor,"Documentation,Stakeholder Management,Project C...","Teamwork,Risk Management","Coordinate projects, manage stakeholders, and ..."
3,J004,Data Insights Associate,Data Analyst,Mumbai,Remote,3,Bachelor,"SQL,Data Analysis,Power BI,Excel","Python,Tableau,Communication,Data Cleaning","Analyze data, build reports, and support decis..."
4,J005,Program Coordinator,Project Manager,Dubai,Hybrid,2,Bachelor,"Documentation,Project Coordination,Communicati...","Jira,Agile","Coordinate projects, manage stakeholders, and ..."
5,J006,Process Analyst,Operations,Delhi,Remote,6,Bachelor,"Reporting,Excel,Process Improvement,Communication","Teamwork,Stakeholder Management","Drive reporting, improve workflows, and suppor..."
6,J007,API Developer,Software Engineer,Pune,Remote,4,Master,"APIs,Python,Git,SQL","Teamwork,Problem Solving","Build backend services, work with APIs, and su..."
7,J008,Operations Associate,Operations,Pune,Onsite,5,Master,"Excel,Process Improvement,Communication,Reporting","Stakeholder Management,Documentation","Drive reporting, improve workflows, and suppor..."
8,J009,Process Analyst,Operations,Hyderabad,Hybrid,5,Bachelor,"Communication,Process Improvement,Reporting,Excel","Teamwork,Documentation,Stakeholder Management,...","Drive reporting, improve workflows, and suppor..."
9,J010,Reporting Analyst,Data Analyst,Hyderabad,Onsite,5,Bachelor,"Excel,SQL,Data Analysis,Power BI","Python,Communication,Data Cleaning,Tableau","Analyze data, build reports, and support decis..."

,application_id,candidate_id,job_id,match_score,application_status,status_date
0,A001,C001,J046,41.5,Matched,2026-01-27
1,A002,C001,J006,56.5,Matched,2026-02-28
2,A003,C002,J020,51.5,Rejected,2026-03-02
3,A004,C002,J051,24.9,Rejected,2026-02-11
4,A005,C002,J032,62.5,Rejected,2026-03-02
5,A006,C003,J033,29.0,Rejected,2026-01-27
6,A007,C003,J024,30.6,Rejected,2026-03-08
7,A008,C003,J051,59.1,Matched,2026-03-01
8,A009,C004,J020,82.5,Interviewed,2026-03-07
9,A010,C004,J053,51.5,Applied,2026-02-28